server:
  port: 8001

spring:
  application:
    name: com.vueDemo.system
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/vueDemo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB



mybatis:
  mapper-locations: classpath:mappers/*.xml

#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  #使用ip注册 客户端用
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

